# AWS Resources Configuration
Resources:
  # Database resources
  HomeDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-home-data
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Service
          Value: tyyacht-api

  # S3 Bucket for file storage
  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.stage}-tyyacht-storage
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            MaxAge: 3000

  # CloudFront Distribution
  CDNDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt FileStorageBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        Enabled: true
        DefaultRootObject: index.html
        Comment: TY Yacht School CDN
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100

  # CloudWatch Log Group
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}
      RetentionInDays: 14

Outputs:
  HomeDataTableName:
    Value: !Ref HomeDataTable
    Export:
      Name: ${self:provider.stage}-home-data-table

  FileStorageBucketName:
    Value: !Ref FileStorageBucket
    Export:
      Name: ${self:provider.stage}-file-storage-bucket

  CDNDistributionDomain:
    Value: !GetAtt CDNDistribution.DomainName
    Export:
      Name: ${self:provider.stage}-cdn-domain